### ISSUE TITLE
Running LspStop in neovim does not supress warnings. 

### ISSUE THREAD

**Issue by SylvanFranklin** [elijah-potter/harper#269] opened 2024-11-05 19:47 UTC
After a fresh install of the latest version via Mason.nvim The out of the box no no config harperLS does not stop running / displaying hints when I run `:LspDisable` in nvim. I may be missing something but since harper is a language server I would expect this command to work.

**Comment by elijah-potter** [comment] 2024-11-05 20:04
This is a duplicate of #139. Please refer there for updates on this.

**Closed by elijah-potter** 2024-11-05 20:04 UTC
Labels: duplicate
