### ISSUE TITLE
Very Minor false positive, rustdoc: plural where singular is a link 

### ISSUE THREAD

**Issue by dvdsk** [elijah-potter/harper#232] opened 2024-10-17 21:08 UTC
```rust
/// You should create multiple  [`Sink`]s.
```

The goal here is to have the word `Sink` be the link since that is the object that is linked to. This shows up in the rendered docs as the word Sinks where the first 4 letters are blue.

Harper currently treats this as the word `Sink` followed by `s.`

**Comment by elijah-potter** [comment] 2024-10-18 03:13
This is a duplicate of #187. Please refer to that issue for updates on this.

**Closed by elijah-potter** 2024-10-18 03:13 UTC
Labels: duplicate
